apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: in-cluster
  namespace: argocd
spec:
  description: Проект для кластера in-cluster
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://188.225.85.118:6443
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: prod2-cluster
  namespace: argocd
spec:
  description: Проект для кластера prod2-cluster
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://94.228.123.177:6443
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
