apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secret
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://kubernetes.default.svc
          - cluster: prod2-cluster
            url: https://94.228.123.177:6443
  template:
    metadata:
      name: secret-{{cluster}}
      namespace: argocd
    spec:
      project: "{{cluster}}"
      source:
        repoURL: https://github.com/nenertiy/react-shop.git
        path: manifests/secret
        targetRevision: HEAD
      destination:
        server: "{{url}}"
        namespace: default

      # syncPolicy:
      #   automated:
      #     prune: true
      #     selfHeal: true
      #   syncOptions:
      #     - CreateNamespace=true
