apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store-second
  namespace: argocd
  annotations:
    argocd.argoproj.io/refresh-interval: "10s"
spec:
  project: default
  source:
    repoURL: https://github.com/nenertiy/react-shop.git
    path: manifests/secret-store
    targetRevision: HEAD
  destination:
    server: https://94.228.123.177:6443
    namespace: vault
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
