apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: default
spec:
  provider:
    vault:
      server: "http://188.225.85.118:30081"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes-second"
          role: "kuber"
          serviceAccountRef:
            name: default
          audience: "vault"
