apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: frontend
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: in-cluster
            url: https://188.225.85.118:6443
          - cluster: prod2-cluster
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: frontend-{{cluster}}
      namespace: argocd
    spec:
      project: "{{cluster}}"
      source:
        repoURL: https://github.com/nenertiy/react-shop.git
        path: manifests/frontend
        targetRevision: HEAD
      destination:
        server: "{{url}}"
        namespace: default

      # syncPolicy:
      #   automated:
      #     prune: true
      #     selfHeal: true
      #   syncOptions:
      #     - CreateNamespace=true
